$(document).ready(function () {
    $("#table").DataTable({
        columns: [
            { title: "Name" },
            { title: "Background" },
            { title: "Skin" },
            { title: "Headwear" },
            { title: "Eyes" },
            { title: "Mouth" },
            { title: "Clothes" },
            { title: "Chain" },
            { title: "Piercings" },
            { title: "Threat Level" },
            { title: "Rank" },
            { title: "View Token" },
        ],
        data: [
            // [
            //     "0",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Mad",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "14",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "1",
            //     "Common",
            //     "Pint",
            //     "Chain $",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "15",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "2",
            //     "Common",
            //     "Watch",
            //     "None",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Bubblegum",
            //     "16",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "3",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Tiedye",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Bubblegum",
            //     "17",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "4",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Bubblegum",
            //     "18",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "5",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "23",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "6",
            //     "Common",
            //     "None",
            //     "None",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "7",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "7",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Pipe",
            //     "8",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "8",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Bulletproof Vest",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Bubblegum",
            //     "9",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "9",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "62",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "10",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Crown",
            //     "Pipe",
            //     "63",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "11",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Bulletproof Vest",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "64",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "12",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Lazer Beams",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "65",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "13",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "95",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "14",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Crown",
            //     "Bubblegum",
            //     "86",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "15",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Smiley Tee",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "87",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "16",
            //     "Cool",
            //     "Gold Brick",
            //     "Chain $",
            //     "Tiedye",
            //     "Piercing",
            //     "Mad",
            //     "Crown",
            //     "Bubblegum",
            //     "88",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "17",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Smiley Tee",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "99",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "18",
            //     "Common",
            //     "None",
            //     "None",
            //     "Tiedye",
            //     "Piercing",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "101",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "19",
            //     "Cool",
            //     "Pint",
            //     "Chain $",
            //     "Bulletproof Vest",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "1",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "20",
            //     "Common",
            //     "Watch",
            //     "None",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Crown",
            //     "Snarl",
            //     "53",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "21",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "None",
            //     "Happy",
            //     "Crown",
            //     "Bubblegum",
            //     "54",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "22",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Tiedye",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Pipe",
            //     "55",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "23",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "56",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "24",
            //     "Rare",
            //     "None",
            //     "Chain",
            //     "Smiley Tee",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "57",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "25",
            //     "Cool",
            //     "None",
            //     "Chain $",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Crown",
            //     "Snarl",
            //     "58",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "26",
            //     "Rare",
            //     "None",
            //     "Chain $",
            //     "Smiley Tee",
            //     "None",
            //     "Lazer Beams",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "59",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "27",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Tiedye",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "5",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "28",
            //     "Common",
            //     "Infinity Gauntlet",
            //     "None",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "41",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "29",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "42",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "30",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "43",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "31",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "44",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "32",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Bubblegum",
            //     "45",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "33",
            //     "Cool",
            //     "Watch",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "46",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "34",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "38",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "35",
            //     "Common",
            //     "None",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "36",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "36",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "37",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "37",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "67",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "38",
            //     "Cool",
            //     "None",
            //     "None",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Snarl",
            //     "39",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "39",
            //     "Common",
            //     "Pint",
            //     "Chain $",
            //     "Smiley Tee",
            //     "None",
            //     "Lazer Beams",
            //     "Unicorn",
            //     "Bubblegum",
            //     "40",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "40",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Tiedye",
            //     "None",
            //     "Mad",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "25",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "41",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Tiedye",
            //     "Piercing",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "26",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "42",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "27",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "43",
            //     "Rare",
            //     "Pint",
            //     "None",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Snarl",
            //     "28",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "44",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Bubblegum",
            //     "29",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "45",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Lakers Jersey",
            //     "None",
            //     "Lazer Beams",
            //     "Unicorn",
            //     "Bubblegum",
            //     "31",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "46",
            //     "Rare",
            //     "Pint",
            //     "None",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "47",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "47",
            //     "Cool",
            //     "Watch",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Lazer Beams",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "48",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "48",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "49",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "49",
            //     "Common",
            //     "None",
            //     "None",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "50",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "50",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Snarl",
            //     "51",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "51",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Bulletproof Vest",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Pipe",
            //     "52",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "52",
            //     "Rare",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "30",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "53",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Tiedye",
            //     "Piercing",
            //     "Lazer Beams",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "66",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "54",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Mad",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "32",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "55",
            //     "UltraRare",
            //     "None",
            //     "Chain $",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Snarl",
            //     "33",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "56",
            //     "Cool",
            //     "Watch",
            //     "None",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Pipe",
            //     "34",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "57",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "35",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "58",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Lazer Beams",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "69",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "59",
            //     "Cool",
            //     "None",
            //     "Chain",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Pipe",
            //     "60",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "60",
            //     "Common",
            //     "None",
            //     "Chain $",
            //     "Smiley Tee",
            //     "None",
            //     "Mad",
            //     "Unicorn",
            //     "Pipe",
            //     "61",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "61",
            //     "Cool",
            //     "None",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Lazer Beams",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "10",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "62",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Smiley Tee",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Snarl",
            //     "11",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "63",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Bulletproof Vest",
            //     "None",
            //     "Mad",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "12",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "64",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "13",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "65",
            //     "Cool",
            //     "Watch",
            //     "Chain",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Snarl",
            //     "71",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "66",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Crown",
            //     "Drippy Grill",
            //     "72",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "67",
            //     "Common",
            //     "None",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Snarl",
            //     "68",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "68",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Tiedye",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "3",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "69",
            //     "Common",
            //     "None",
            //     "None",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Snarl",
            //     "70",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "70",
            //     "Common",
            //     "Watch",
            //     "Chain",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "24",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "71",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Bubblegum",
            //     "6",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "72",
            //     "Cool",
            //     "None",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "73",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "73",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Smiley Tee",
            //     "None",
            //     "Mad",
            //     "Unicorn",
            //     "Pipe",
            //     "74",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "74",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Crown",
            //     "Drippy Grill",
            //     "19",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "75",
            //     "Common",
            //     "None",
            //     "None",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Bubblegum",
            //     "20",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "76",
            //     "Common",
            //     "None",
            //     "None",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "21",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "77",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "22",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "78",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "2",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "79",
            //     "Common",
            //     "None",
            //     "None",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "89",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "80",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Bulletproof Vest",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "90",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "81",
            //     "Cool",
            //     "Gold Brick",
            //     "Chain",
            //     "Bulletproof Vest",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "91",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "82",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Tiedye",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "92",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "83",
            //     "Cool",
            //     "None",
            //     "None",
            //     "Tiedye",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "93",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "84",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Pipe",
            //     "94",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "85",
            //     "Common",
            //     "None",
            //     "Chain $",
            //     "Tiedye",
            //     "Piercing",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "4",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "86",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Bubblegum",
            //     "96",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "87",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Tiedye",
            //     "None",
            //     "Mad",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "97",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "88",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Smiley Tee",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "98",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "89",
            //     "Common",
            //     "None",
            //     "None",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Happy",
            //     "Crown",
            //     "Bubblegum",
            //     "100",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "90",
            //     "Rare",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "75",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "91",
            //     "Cool",
            //     "Pint",
            //     "Chain",
            //     "Smiley Tee",
            //     "None",
            //     "Mad",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "76",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "92",
            //     "Common",
            //     "None",
            //     "Chain",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Happy",
            //     "Pirate Hat",
            //     "Pipe",
            //     "77",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "93",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Lakers Jersey",
            //     "Piercing",
            //     "Mad",
            //     "Pirate Hat",
            //     "Bubblegum",
            //     "78",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "94",
            //     "Cool",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "79",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "95",
            //     "Common",
            //     "None",
            //     "None",
            //     "Tiedye",
            //     "Piercing",
            //     "Mad",
            //     "Unicorn",
            //     "Drippy Grill",
            //     "80",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "96",
            //     "Rare",
            //     "None",
            //     "None",
            //     "Golf Shirt",
            //     "None",
            //     "Happy",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "81",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "97",
            //     "Common",
            //     "Pint",
            //     "Chain $",
            //     "Smiley Tee",
            //     "Piercing",
            //     "Lazer Beams",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "82",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "98",
            //     "Common",
            //     "Pint",
            //     "Chain",
            //     "Lakers Jersey",
            //     "None",
            //     "Happy",
            //     "Crown",
            //     "Drippy Grill",
            //     "83",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "99",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "Piercing",
            //     "Lazer Beams",
            //     "Pirate Hat",
            //     "Drippy Grill",
            //     "84",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
            // [
            //     "100",
            //     "Common",
            //     "Pint",
            //     "None",
            //     "Golf Shirt",
            //     "Piercing",
            //     "None",
            //     "None",
            //     "None",
            //     "85",
            //     "<a href='https://solscan.io' style='text-decoration: none; font-size: 10px; color:white;' target='_blank' ><img src='art/unknownBox.png' width='80%'' height='80%'/><br>View Token</a>",
            // ],
        ],
        iDisplayLength: -1,
        sScrollX: "100%",
        sScrollXInner: "100%",
        lengthMenu: [
        ],
        paging: true,
        scrollY: "70vh",
        dom: "Bfrtip",
    });
});